
D:\code\deeplearn\src\unet-master
(dlenv) λ python m2.py
2020-10-28 15:11:21.803746: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-10-28 15:11:22.191533: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-10-28 15:11:53.256662: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2020-10-28 15:11:53.272618: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2020-10-28 15:11:53.342639: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: LAPTOP-2HNJGF5D
2020-10-28 15:11:53.356920: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: LAPTOP-2HNJGF5D
2020-10-28 15:11:53.367651: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-10-28 15:11:53.471891: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x19b05bcd7b0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-10-28 15:11:53.496316: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
WARNING:tensorflow:From m2.py:18: Model.fit_generator (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.
Instructions for updating:
Please use Model.fit, which supports generators.
Found 30 images belonging to 1 classes.
Found 0 images belonging to 1 classes.
Traceback (most recent call last):
  File "m2.py", line 18, in <module>
    model.fit_generator(myGene,steps_per_epoch=300,epochs=1,callbacks=[model_checkpoint])
  File "D:\code\deeplearn\dlenv\dlenv\lib\site-packages\tensorflow\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "D:\code\deeplearn\dlenv\dlenv\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1815, in fit_generator
    return self.fit(
  File "D:\code\deeplearn\dlenv\dlenv\lib\site-packages\tensorflow\python\keras\engine\training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "D:\code\deeplearn\dlenv\dlenv\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1098, in fit
    tmp_logs = train_function(iterator)
  File "D:\code\deeplearn\dlenv\dlenv\lib\site-packages\tensorflow\python\eager\def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "D:\code\deeplearn\dlenv\dlenv\lib\site-packages\tensorflow\python\eager\def_function.py", line 840, in _call
    return self._stateless_fn(*args, **kwds)
  File "D:\code\deeplearn\dlenv\dlenv\lib\site-packages\tensorflow\python\eager\function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "D:\code\deeplearn\dlenv\dlenv\lib\site-packages\tensorflow\python\eager\function.py", line 1843, in _filtered_call
    return self._call_flat(
  File "D:\code\deeplearn\dlenv\dlenv\lib\site-packages\tensorflow\python\eager\function.py", line 1923, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "D:\code\deeplearn\dlenv\dlenv\lib\site-packages\tensorflow\python\eager\function.py", line 545, in call
    outputs = execute.execute(
  File "D:\code\deeplearn\dlenv\dlenv\lib\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Incompatible shapes: [2,256,256,1] vs. [0,256,256,1]
         [[node gradient_tape/binary_crossentropy/logistic_loss/mul/BroadcastGradientArgs (defined at m2.py:18) ]] [Op:__inference_train_function_2987]

Function call stack:
train_function

2020-10-28 15:11:58.265485: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
         [[{{node PyFunc}}]]

D:\code\deeplearn\src\unet-master
(dlenv) λ
